version: '3.8'

services:
  incident-management-service:
    build:
      context: ./incident-service
      dockerfile: Dockerfile
    image: incident-management-service:1
    container_name: incident-management-service
    ports:
      - "8080:8080"
    environment:
      - INCIDENT_SERVICE_HOST=incident-management-service  

  web-portal:
    build:
      context: ./web-portal
      dockerfile: Dockerfile
    image: web-portal:1
    container_name: web-portal
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://incident-management-service:8080  # Connects to backend
    depends_on:
      - incident-management-service  # Ensure backend starts before frontend