spring:
  application.name: incident
  datasource:
    url: jdbc:h2:mem:incident
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      env_schema: PUBLIC