spring:
  application.name: incident
  datasource:
    url: jdbc:h2:mem:incident
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      env_schema: PUBLIC
  cache:
    jcache:
      config: classpath:ehcache.xml