FROM eclipse-temurin:17-jdk AS build
WORKDIR /app

COPY mvnw ./
COPY pom.xml ./

RUN ./mvnw dependecy:resolve

COPY src ./src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jre AS runtime
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
