FROM eclipse-temurin:17-jdk AS build
WORKDIR /app/incident-service

COPY mvnw ./
COPY pom.xml ./
COPY src ./src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jre AS runtime

COPY --from=build /app/incident-service/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
